server:
  port: 8999

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/api/v1/contact/**

            
# we need to configure the routes and the appropiate service to call for those  routes
# so uri will be lb://user-service i.e. loadbalancer to use user-service when
# the path contains /user  (id should be the name of those microservices)
#same goes fr contact-service